[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook_frontier = "CMkFe7d5cwEHX9uuwjNhKYbT3kDN2dezHtfgmgHZFdVi"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
